server:
  port: 8080
  servlet:
    context-path: /sell

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://118.89.182.204:3306/sell_db?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
#  redis:
#    host: 192.168.30.113
#    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wxc3a72fffe7db3d44
  mpAppSecret: c068b992d5c5cd09a32e012f09396510
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://wc.chainof.cn/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.soon.model

project-url:
  wechatMpAuthorize: http://wc.chainof.cn
  wechatOpenAuthorize: http://wc.chainof.cn
  sell: http://wc.chainof.cn


#pagehelper分页插件配置
#  pagehelper.helperDialect=mysql
#  pagehelper.reasonable=true
#  pagehelper.supportMethodsArguments=true
#  pagehelper.params=count=countSql